# fly.toml app configuration file generated for item-packer-inc on 2025-06-25T02:41:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'item-packer-inc'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
