// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order/items/{amount}": {
            "post": {
                "description": "Create an order with the specified number of items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create an order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    },
                    "400": {
                        "description": "Invalid amount",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "No packs available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/packs": {
            "get": {
                "description": "Get a list of all available packs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packs"
                ],
                "summary": "Get all available packs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pack"
                            }
                        }
                    }
                }
            }
        },
        "/packs/{amount}": {
            "post": {
                "description": "Add a new pack with the specified amount",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packs"
                ],
                "summary": "Add a new pack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack amount",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Pack"
                        }
                    },
                    "400": {
                        "description": "Invalid amount",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Limit for packs reached",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a pack with the specified amount",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packs"
                ],
                "summary": "Delete a pack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack amount",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid amount",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/packs/{oldAmount}/{newAmount}": {
            "put": {
                "description": "Update a pack's amount",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packs"
                ],
                "summary": "Update a pack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Current pack amount",
                        "name": "oldAmount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "New pack amount",
                        "name": "newAmount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pack"
                        }
                    },
                    "400": {
                        "description": "Invalid amount",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Pack with new amount already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Order": {
            "type": "object",
            "properties": {
                "overpackedItems": {
                    "type": "integer"
                },
                "packs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderPack"
                    }
                },
                "requestedItems": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                }
            }
        },
        "models.OrderPack": {
            "type": "object",
            "properties": {
                "pack": {
                    "$ref": "#/definitions/models.Pack"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "models.Pack": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Item Packer API",
	Description:      "API for packing items into standard sized packs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
